### ISSUE TITLE
User Impersonation For Whole Process

### ISSUE THREAD

**Issue by GulsahYalcin** [Waffle/waffle#1782]
I am using Waffle 1.8 version, because my current project is running with Java 1.7.

I want to impersonate to a user for whole process but my current usage provides impersonation for the current thread. Therefore I need to call following block of code for every thread. How can I make impersonation for whole process? Thanks in advace.  

WindowsAuthProviderImpl provider = new WindowsAuthProviderImpl();		
		
IWindowsIdentity identity = provider.logonDomainUserEx(name, domain, password, WinBase.LOGON32_LOGON_NEW_CREDENTIALS,
				      WinBase.LOGON32_PROVIDER_DEFAULT);
				
IWindowsImpersonationContext context = identity.impersonate();

**Comment by hazendaz** [comment]
Not much I can help with there given the age, certainly check the docs here and the user group noted.

If the issue is with version of waffle, not much help can be provided here.  Java 7 is not supported by any vendor at this point.  This framework hasn't supported it in years.  1.8 is 7 years old release of waffle.  I'd fully expect all kinds of issues with it on any modern windows distribution.  You could though use 1.8.3 from the newer group id https://search.maven.org/search?q=g:com.github.waffle%20AND%20a:waffle-jna.  Its likely to still have problems though as a lot of important fixes over the  years landed in newer versions.  Your best bet would be to get at to java 8.  Also look at change log, I don't recall off hand specifics on major changes but seem to think impersonation might have had changes since 1.8 days.

**Comment by GulsahYalcin** [comment]
Thanks for quick response

**Comment by dblock** [comment]
What's your scenario @GulsahYalcin?

AFAIK Windows doesn't provide "whole process impersonation", you would need to start a process under that user and then all threads in that process would run as that user.

**Comment by GulsahYalcin** [comment]
In my project, we have a shared folder over network, but this folder is shared only with a specific AD user for security issues. My Windows Java application needs to access this folder time to time, from different threads. As you said, I need to run this application with this specific user credientials. I tried to first write a small script,  run this app by using RunAs tool of windows, but It pop-ups a window to enter password, which is not okay for me. I need to do this silently and RunAs tool doesn't take any input for password. 

Then, I try to use waffle, to make user impersonation inside process but I needed to make impersonation at start of every thread.

Btw, I also try to start my application inside a thread in which user impersonation is done via waffle. 
 
Thread 1: 
--- First do impersonation with waffle
--- Then call; cmd /c MyApp.exe ....

But this also does not work. 

Is there any other way to start process under a specific user that you know?

Thanks in advance.

**Comment by dblock** [comment]
Waffle would be a very complicated way to do this. If you have a user password, you can run as that user with other tools. Have you looked at https://stackoverflow.com/questions/12456675/single-line-command-for-run-as-a-different-user-on-windows-7-that-contains-a-pas/12456756#12456756? People are recommending [psexec](https://learn.microsoft.com/en-us/sysinternals/downloads/psexec). 

Now, you'll be storing a password for the user that has access to the folder? That seems to be the least secure way to do it. It's definitely a lot worse than giving the user that runs the app access to the folder.

**Comment by GulsahYalcin** [comment]
I solved my problem by using psexec as you also mentioned. 

Yes, we will be storing password for that user by encrypting it, but still we need to reconsider this solution.

Thank you very much for your advices and time.

**Comment by dblock** [comment]
> Yes, we will be storing password for that user by encrypting it, but still we need to reconsider this solution.

This wouldn't pass a security review in my world. Storing passwords in any form or shape is a no.
