### ISSUE TITLE
Add .net waffle to nuget.org

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Waffle/waffle#267]
Lib seems convenient. If on nuget I can just get it and script NAS from F# under some user credentials.

**Comment by simon-p-r** [comment]
Will you accept a PR for this?

**Comment by hazendaz** [comment]
Yes I'll accept a  PR for this.  If you can write up instructions as well for our docs to help maintainers. Thanks

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by dblock** [comment]
Related #510

**Comment by hazendaz** [comment]
Released to nuget but not completely done to close this task...

In nuget, this is the package for install...

Install-Package Waffle.AD

Still need some documentation of the process.

Here is how it was uploaded using our current project as it includes nuget from the root using powershell.

./nuget.exe push Waffle.AD.1.8.3.nupkg ${apikeyhere} -Source https://www.nuget.org/api/v2/package

Here is how it is packed for uploading...

./nuget.exe pack Waffle.nuspec

This creates Waffle.AD.1.8.3.nupkg in the root.

I'd like to get that out of the root and into a folder that is already ignored but for time being added it to gitignore.  

To test downloading this, add it to the 'bootstrap.cmd'

NuGet.exe install Waffle.AD -OutputDirectory .nuget\packages\ -NonInteractive -Version 1.8.3

Probably need some help with a project using nuget to make sure this is setup properly.  This otherwise seems like the right path.

**Comment by hazendaz** [comment]
Closing task will open a new one for documentation needs.
