### ISSUE TITLE
Waffle as its own organization

### ISSUE THREAD

**Issue by dblock** [Waffle/waffle#391]
Similar to what [I did for oshi](https://github.com/oshi/oshi/issues/251), I'd like to create/see created a Waffle organization and donate waffle into it. An org allows repo owners to add/remove people, and therefore reduce the bus factor. Similarly, orgs would allow to have good grouping around projects.

If someone wants to setup the org and add me as co-owner, I will transfer the project!

**Comment by dblock** [comment]
cc: @hazendaz thoughts? Want to create it?

**Comment by hazendaz** [comment]
Sure.  I think waffle is already an org for another project so might need to adjust naming.  Im traveling currently and will be back home in another week.

Jeremy

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Sep 26, 2016 at 10:40 AM -0400, "Daniel Doubrovkine (dB.) @dblockdotorg" <notifications@github.com<mailto:notifications@github.com>> wrote:


cc: @hazendaz<https://github.com/hazendaz> thoughts? Want to create it?

-

**Comment by hazendaz** [comment]
trying to get waffle location in github given over to us.  Unused location currently with two empty repos.  Here is my request.  If I don't get an answer, I could go one of two ways.  One to report it as abuse since it clearly conflicts with our repo name without usage (least appropriate) and second is to simply rename our project level to something else such as 'waffle-active-directory'.

https://github.com/Waffle/waffle-app/issues/1

**Comment by dblock** [comment]
Since github.com/waffle is clearly a placeholder with two empty projects I am confident github would pull it if you ask support - there's lots of precedent for that.

**Comment by hazendaz** [comment]
@dblock ownership changed peacefully.  Sent you an invite.

**Comment by dblock** [comment]
I've transferred the repo, party on!

**Comment by hazendaz** [comment]
Transfer complete, java side switched from 'dblock' to 'waffle'.  Will keep this open a bit longer until I've had time to go through all the non java files to switch over.

**Comment by hazendaz** [comment]
All good here.  Closing issue.
