### ISSUE TITLE
https://waffle.github.io/waffle not published since 2015?

### ISSUE THREAD

**Issue by dblock** [Waffle/waffle#597]
https://waffle.github.io/waffle/

**Comment by hazendaz** [comment]
@dblock I had not noticed this the last few releases.  I suspect the site plugin we are using is silently error'ing out.  I'll push out an updated site manually today and then will look into the overall issue.

**Comment by hazendaz** [comment]
I'm having some troubles on my machine with site deploy.  I'm getting a negotiation error no matter the project.  I'll have to do some research to figure out what is going on...once I get that resolved, I'll work on getting this site going again.

**Comment by hazendaz** [comment]
Latest is in process of publishing now.  I think the issue was using https for site rather than ssh along with 2.0.4 version of wagon-git which is known to have issues.  I've dropped that back to 2.0.3 and applied ssh so now seems like it will release fine going forwards.  I'll send a PR shortly with those two changes.  Vast majority of the new site is up and likely to be completed in next 15 minutes.
