### ISSUE TITLE
Add BOM that can be used for dependencyManagement import

### ISSUE THREAD

**Issue by cebaa** [Waffle/waffle#765]
Similar to

```
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
```

**Comment by hazendaz** [comment]
What benefit will that provide here?  General usage of waffle only would be one artifact listed in pom. Spring boot is incredibly different and as such not a good comparison.   I'm not seeing the usefulness.  More info and a possible PR showing why would be helpful.  Im not against it as long as the value is there.  Thanks.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Issue resolved by simply fixing the spring boot 2 module to reference correct spring security.

**Comment by hazendaz** [comment]
@cebaa I have added a bom to the project which is a subset of the distro module.  There was also some more minor mistakes in what was pulled for spring boot 1 vs 2.  I don't think the added bom as is or distro do a good job of getting right transients.  That is highly due to us supporting lots of different versions.  I many need to have multiple boms and it's a bit tricky to what we resolve with the mixed content otherwise.  All the main modules though should properly resolve everything necessary as of lastest master.  I'll likely be releasing in next week or two.
